/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDocsRouteImport } from './routes/admin.docs'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminRegistrationsIndexRouteImport } from './routes/admin.registrations.index'
import { Route as ApiPublicUazapiWebhookRouteImport } from './routes/api/public/uazapi-webhook'
import { Route as AdminRegistrationsIdRouteImport } from './routes/admin.registrations.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsIndexRoute = AdminRegistrationsIndexRouteImport.update({
  id: '/registrations/',
  path: '/registrations/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicUazapiWebhookRoute = ApiPublicUazapiWebhookRouteImport.update({
  id: '/api/public/uazapi-webhook',
  path: '/api/public/uazapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsIdRoute = AdminRegistrationsIdRouteImport.update({
  id: '/registrations/$id',
  path: '/registrations/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/admin/registrations/': typeof AdminRegistrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/r/$slug': typeof RSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/admin/registrations': typeof AdminRegistrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/admin/registrations/': typeof AdminRegistrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/devices'
    | '/admin/diagnostics'
    | '/admin/docs'
    | '/admin/login'
    | '/admin/whatsapp'
    | '/r/$slug'
    | '/admin/'
    | '/admin/registrations/$id'
    | '/api/public/uazapi-webhook'
    | '/admin/registrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/devices'
    | '/admin/diagnostics'
    | '/admin/docs'
    | '/admin/login'
    | '/admin/whatsapp'
    | '/r/$slug'
    | '/admin'
    | '/admin/registrations/$id'
    | '/api/public/uazapi-webhook'
    | '/admin/registrations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/devices'
    | '/admin/diagnostics'
    | '/admin/docs'
    | '/admin/login'
    | '/admin/whatsapp'
    | '/r/$slug'
    | '/admin/'
    | '/admin/registrations/$id'
    | '/api/public/uazapi-webhook'
    | '/admin/registrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RSlugRoute: typeof RSlugRoute
  ApiPublicUazapiWebhookRoute: typeof ApiPublicUazapiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations/': {
      id: '/admin/registrations/'
      path: '/registrations'
      fullPath: '/admin/registrations/'
      preLoaderRoute: typeof AdminRegistrationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/uazapi-webhook': {
      id: '/api/public/uazapi-webhook'
      path: '/api/public/uazapi-webhook'
      fullPath: '/api/public/uazapi-webhook'
      preLoaderRoute: typeof ApiPublicUazapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations/$id': {
      id: '/admin/registrations/$id'
      path: '/registrations/$id'
      fullPath: '/admin/registrations/$id'
      preLoaderRoute: typeof AdminRegistrationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRegistrationsIdRoute: typeof AdminRegistrationsIdRoute
  AdminRegistrationsIndexRoute: typeof AdminRegistrationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDevicesRoute: AdminDevicesRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRegistrationsIdRoute: AdminRegistrationsIdRoute,
  AdminRegistrationsIndexRoute: AdminRegistrationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RSlugRoute: RSlugRoute,
  ApiPublicUazapiWebhookRoute: ApiPublicUazapiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
